# Generated by Django 4.1.5 on 2023-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], max_length=50)),
            ],
        ),
    ]
